In [2]:
import numpy as np
import pandas as pd
from sap_conn import get_conn
from sap_rtab import rfc_read_table
import time
from datetime import datetime
from datetime import date, timedelta

from py_rfc_methods import get_delivery_plants_df

In [3]:
def create_paths(zsdkap_report_name, zsbe_report_name, mb5t_report_name, mb52_report_name, zkbp1_report_name):
    global ZSDKAP_FILE_PATH, ZSBE_FILE_PATH, MB5TD_2101, KPIS_FILE_PATH, MB52_FILE_PATH, ZKBP1_FILE_PATH
    # ZSDKAP_FILE_PATH = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty\28_PPS_KPI\excel_files/job/{zsdkap_report_name}.csv'
    # ZSBE_FILE_PATH = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty\28_PPS_KPI\excel_files/job/{zsbe_report_name}.xlsx'
    # MB5TD_2101 = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty/28_PPS_KPI\excel_files/job/{mb5t_report_name}.xlsx'
    # MB52_FILE_PATH = f'C:/Temp/Kamil/Prywatne/07_Programowanie/99_Moje_projekty/28_PPS_KPI/excel_files/job/{mb52_report_name}.xlsx'

    # ZSDKAP_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zsdkap_report_name}.csv'
    # ZSBE_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zsbe_report_name}.xlsx'
    # MB5TD_2101 = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{mb5t_report_name}.xlsx'
    # MB52_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{mb52_report_name}.xlsx'
    # ZKBP1_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zkbp1_report_name}.xlsx'

    ZSDKAP_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT\test_k11/{zsdkap_report_name}.csv'
    ZSBE_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT\test_k11/{zsbe_report_name}.xlsx'
    MB5TD_2101 = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT\test_k11/{mb5t_report_name}.xlsx'
    MB52_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT\test_k11/{mb52_report_name}.xlsx'
    ZKBP1_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT\test_k11/{zkbp1_report_name}.xlsx'

In [4]:
zsdkap_report_name="zsdkap_20260626_REP_LU_PPS001A"
zsbe_report_name= "zsbe_mont"
mb5t_report_name= "MB5TD_2101"
mb52_report_name="mb52"
zkbp1_report_name='ZKBP1_SB_0301'

create_paths(zsdkap_report_name, zsbe_report_name, mb5t_report_name, mb52_report_name, zkbp1_report_name)

In [5]:
# SAP_SYSTEM = "P11_SSO"
SAP_SYSTEM = "K11"

In [6]:
from maps import vbap_new_columns_names, zsdkap_dtypes, zsdkap_new_columns_names, production_site_map
from shipping_logic import get_production_shipping_date


def load_open_orders_and_adjust_dispatch_date(file_path):
    raw_df = pd.read_csv(file_path, dtype=zsdkap_dtypes, sep=';', encoding='MacRoman')
    raw_df['WADAT'] = pd.to_datetime(raw_df['WADAT'], dayfirst=True, errors='coerce')
    raw_df = raw_df.rename(columns=zsdkap_new_columns_names)
    # TODO: Here implement dispatch date recalculation
    raw_df['production_site'] = raw_df['mrp_controller'].apply(lambda mrp: production_site_map.get(mrp))
    delivery_plants = get_delivery_plants_df(SAP_SYSTEM, raw_df['customer_order_number'].tolist(), 1000, 100)
    delivery_plants = delivery_plants.rename(columns=vbap_new_columns_names)
    raw_df = pd.merge(raw_df, delivery_plants, how='left', on=['customer_order_number', 'customer_order_position'])
    raw_df.dropna(subset=['production_site', 'delivery_plant'], inplace=True)
    # raw_df.to_excel(f"{OUTPUT_FILE_PATH}/before-implementation.xlsx")
    raw_df['dispatch_date'] = raw_df.apply(
        lambda row: get_production_shipping_date(row['dispatch_date_original'], row['production_site'],
                                                 row['delivery_plant']), axis=1)

    return raw_df


def fill_general_stock_information(df):
    df['special_stock_indicator'] = df['special_stock_indicator'].replace('', 'general_stock')
    # df['customer_order_number_original'] = df['customer_order_number']
    # df['customer_order_position_original'] = df['customer_order_position']
    #
    # # Filter rows where special stock indicator is 'general_stock'
    # condition = df['special_stock_indicator'] == 'general_stock'
    #
    # # Update target columns for the filtered rows
    # df.loc[condition, ['customer_order_number', 'customer_order_position']] = 'general_stock_position'

    return df

In [7]:
from maps import mb5td_new_columns_names, mb5td_dtypes, ekkn_new_columns_names
from py_rfc_methods import get_purchase_order_sales_orders


def get_mb5t_df():
    # TODO: Specify correct MB5TD file (either 2101 or 0301)
    mb5t_df = pd.read_excel(MB5TD_2101, sheet_name='Exported data', dtype=mb5td_dtypes)
    mb5t_df = mb5t_df.rename(columns=mb5td_new_columns_names)

    po_list = mb5t_df[mb5t_df['special_stock_indicator'] == 'E']['purchase_order_number'].tolist()
    sales_orders = get_purchase_order_sales_orders(SAP_SYSTEM, po_list)
    sales_orders = sales_orders.rename(columns=ekkn_new_columns_names)

    mb5t_df = mb5t_df.merge(sales_orders, how='left', on=['purchase_order_number', 'purchase_order_position'])

    mb5t_df = mb5t_df[['mat_number', 'transit_quantity', 'customer_order_number', 'customer_order_position', 'plant']]
    # mb5t_df = mb5t_df.groupby('mat_number', as_index=False).sum()

    return mb5t_df

In [8]:
mb5t = get_mb5t_df()

2026-06-26 14:51:49 | INFO     | SAP_CONN | Buduję parametry dla systemu K11: {'mshost': 'rffsk11s.sap.roto-frank.com', 'msserv': '3602', 'sysid': 'K11', 'group': 'ROTO_FRANK', 'client': '151', 'lang': 'PL', 'snc_mode': '1', 'snc_qop': '8', 'snc_partnername': ' ', 'timeout': '300'}
2026-06-26 14:51:50 | INFO     | SAP_CONN | Połączenie z SAP nawiązane (system=K11).
2026-06-26 14:51:50 | INFO     | SAP_CONN | Połączenie SAP zamknięte (system=K11).

In [18]:
mb5t[mb5t['mat_number'] == '808965'].head(25)

,mat_number,transit_quantity,customer_order_number,customer_order_position,plant
9,808965,8.0,NaN,NaN,3701
10,808965,24.0,NaN,NaN,3701

In [10]:
from maps import mb52_new_columns_names, mb52_dtypes


def get_mb52_df():
    mb52_df = pd.read_excel(MB52_FILE_PATH, sheet_name='Exported data', dtype=mb52_dtypes)
    mb52_df = mb52_df.rename(columns=mb52_new_columns_names)

    mb52_df["customer_order_number"] = (
        mb52_df["customer_order_number"].str.zfill(10)
    )

    return mb52_df

mb52_df = get_mb52_df()

In [16]:
mb52_df[mb52_df['customer_order_number'].isna()]

,mat_number,Opis,stock_quantity,storage_location,Podst.JM,Zablokowane,W kontr.jakości,customer_order_number,customer_order_position,plant
0,2044558,Glasfalzeinlage Sonderverglasung 4mm,45850.000,0003,SZT,39000.00,0,<NA>,000000,0301
1,360041,Sprężyna 2000 H/K 05/07,1748.000,0610,SZT,950.00,0,<NA>,000000,0301
2,729796,NaN,637.363,0002,M2,693.36,0,<NA>,000000,0301
3,108232,Karton EDR 1300x334x110 G2,954.000,0003,SZT,420.00,0,<NA>,000000,0301
4,2036469,Panzer 07/11 R703 RT2 Rx_E,169.000,0003,SZT,99.00,0,<NA>,000000,0301
...,...,...,...,...,...,...,...,...,...,...
19272,GP,Euro-Gitterboxpalette,11.000,0100,SZT,0.00,0,<NA>,000000,0301
19273,KP160,ROTO gitterbox 160x80cm,2.000,<NA>,SZT,0.00,0,<NA>,000000,0301
19274,KP160,ROTO gitterbox 160x80cm,48.000,<NA>,SZT,0.00,0,<NA>,000000,0301
19275,KP160,ROTO gitterbox 160x80cm,9.000,<NA>,SZT,0.00,0,<NA>,000000,0301
19276,KP160,ROTO gitterbox 160x80cm,-59.000,0100,SZT,0.00,0,<NA>,000000,0301