In [1]:
import pandas as pd
from datetime import datetime
from datetime import date, timedelta

In [2]:
zkbp1_dtypes = {
    'L.poj.aktiv': 'float',
    'Zawart pojemn': 'float',
}

zkbp1_new_columns_names = {
    'NrMat.': 'mat_number',
    'L.poj.aktiv': 'num_of_containers',
    'Zawart pojemn': 'container_capacity',
    'Krótki tekst mater.:': 'mat_name'
}

zsbe_dtypes = {
    'Materiał': 'string',
    'Zakład': 'string',
    'Column': 'float',
    'Column 2': 'float',
}

zsbe_new_columns_names = {
    'Materiał': 'mat_number',
    'Zakład': 'plant',
    'Column': 'stock_quantity',
    'Kontroler MRP': 'mrp_controller',
    'Column 2': 'safety_stock',
}

In [3]:
def create_paths(zsdkap_report_name, zsbe_report_name, mb5t_report_name, mb52_report_name, zkbp1_report_name):
    global ZSDKAP_FILE_PATH, ZSBE_FILE_PATH, MB5TD_2101, KPIS_FILE_PATH, MB52_FILE_PATH, ZKBP1_FILE_PATH
    # ZSDKAP_FILE_PATH = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty\28_PPS_KPI\excel_files/job/{zsdkap_report_name}.csv'
    # ZSBE_FILE_PATH = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty\28_PPS_KPI\excel_files/job/{zsbe_report_name}.xlsx'
    # MB5TD_2101 = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty/28_PPS_KPI\excel_files/job/{mb5t_report_name}.xlsx'
    # MB52_FILE_PATH = f'C:/Temp/Kamil/Prywatne/07_Programowanie/99_Moje_projekty/28_PPS_KPI/excel_files/job/{mb52_report_name}.xlsx'

    ZSDKAP_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zsdkap_report_name}.csv'
    ZSBE_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zsbe_report_name}.xlsx'
    MB5TD_2101 = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{mb5t_report_name}.xlsx'
    MB52_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{mb52_report_name}.xlsx'
    ZKBP1_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zkbp1_report_name}.xlsx'

In [4]:
zsdkap_report_name="zsdkap"
zsbe_report_name= "zsbe_mont"
mb5t_report_name= "MB5TD_0301"
mb52_report_name="mb52"
zkbp1_report_name='ZKBP1_SB_0301'

create_paths(zsdkap_report_name, zsbe_report_name, mb5t_report_name, mb52_report_name, zkbp1_report_name)

In [5]:
zkbp1_df = pd.read_excel(ZKBP1_FILE_PATH, sheet_name='Exported data', dtype=zkbp1_dtypes)
zkbp1_df = zkbp1_df.rename(columns=zkbp1_new_columns_names)
zkbp1_df['mat_number'] = zkbp1_df['mat_number'].astype(str)
zkbp1_df['safety_stock_kanban'] = zkbp1_df['num_of_containers'] * zkbp1_df['container_capacity']
zkbp1_df['plant'] = "0301"
zkbp1_df = zkbp1_df[[
    'mat_number',
    'safety_stock_kanban',
    'plant',]]

In [6]:
zkbp1_df

    mat_number  safety_stock_kanban plant
0       739371                 24.0  0301
1       810031                 12.0  0301
2       810032                 12.0  0301
3       810033                 12.0  0301
4       810034                 12.0  0301
..         ...                  ...   ...
557     537939                 30.0  0301
558     537987                 12.0  0301
559     538143                 12.0  0301
560     538155                 12.0  0301
561     537723                 18.0  0301

[562 rows x 3 columns]

In [7]:
# zkbp1_df[zkbp1_df['mat_number'] == "632229"]
zkbp1_df[zkbp1_df['mat_number'] == "782623"]

    mat_number  safety_stock_kanban plant
460     782623                 48.0  0301

In [16]:
# mrp_controller = ('M81', 'M82')
mrp_controller = ('MQ1', 'MQ2')

zsbe_df = pd.read_excel(ZSBE_FILE_PATH, sheet_name='Exported data', dtype=zsbe_dtypes)
zsbe_df = zsbe_df.rename(columns=zsbe_new_columns_names)
zsbe_df = zsbe_df[(zsbe_df['mrp_controller'].isin(mrp_controller)) & (~zsbe_df['mat_number'].str.startswith('99'))]
zsbe_df = zsbe_df[['mat_number', 'stock_quantity', 'safety_stock', 'plant']]

In [17]:
zsbe_df.sort_values(by='stock_quantity', ascending=False)

Empty DataFrame
Columns: [mat_number, stock_quantity, safety_stock, plant]
Index: []

In [66]:
zsbe_zkbp1_merged = pd.merge(zsbe_df, zkbp1_df, on=['mat_number', 'plant'], how='left')
zsbe_zkbp1_merged['safety_stock_kanban'] = zsbe_zkbp1_merged['safety_stock_kanban'].fillna(0)
zsbe_zkbp1_merged['safety_stock'] = zsbe_zkbp1_merged['safety_stock'] + zsbe_zkbp1_merged['safety_stock_kanban']
zsbe_zkbp1_merged = zsbe_zkbp1_merged[['mat_number', 'stock_quantity', 'safety_stock']]
zsbe_zkbp1_merged

In [67]:
zsbe_zkbp1_merged.dtypes

mat_number         object
stock_quantity    float64
safety_stock      float64
dtype: object

In [6]:
str("https://teams.microsoft.com/l/message/19:d524e2ec24cf4f82949ef2a0f0599ca4@thread.tacv2/1766854268203?tenantId=7b261e37-ae24-4029-a4f5-07ab8831a3a5&groupId=a1d38132-407e-416f-8b1c-9b210b1b642d&parentMessageId=1766854268203").split('=')[3]

'1766854268203'

In [10]:
# data = {"A": [1, 2, 3],
#         "B": [4, 5, 6], }
data = {"A": [], "B": []}
df = pd.DataFrame(data, columns=['A', 'B'])

In [11]:
column_data = df['A']
if column_data.empty:
    column_data = pd.Series(["808965"])
column_data

0    808965
dtype: object