In [75]:
import pandas as pd
from sap_conn import get_conn
from sap_rtab import rfc_read_table
import time
from datetime import datetime
from datetime import date, timedelta

from py_rfc_methods import get_delivery_plants_df

In [76]:
zkbp1_dtypes = {
    'L.poj.aktiv': 'float',
    'Zawart pojemn': 'float',
}

zkbp1_new_columns_names = {
    'NrMat.': 'mat_number',
    'L.poj.aktiv': 'num_of_containers',
    'Zawart pojemn': 'container_capacity',
    'Krótki tekst mater.:': 'mat_name'
}

zsbe_dtypes = {
    'Materiał': 'string',
    'Zakład': 'string',
    'Column': 'float',
    'Column 2': 'float',
}

zsbe_new_columns_names = {
    'Materiał': 'mat_number',
    'Zakład': 'plant',
    'Column': 'stock_quantity',
    'Kontroler MRP': 'mrp_controller',
    'Column 2': 'safety_stock',
}

production_site_map = {
    # Production site 2101
    'L1K': '2101',
    'L1H': '2101',
    'L41': '2101',
    'L3H': '2101',
    'L82': '2101',
    'L2H': '2101',
    'LD1': '2101',
    'LZ1': '2101',
    'LMD': '2101',
    'LAS': '2101',
    'L2E': '2101',
    'L2V': '2101',
    'LI1': '2101',
    'LI3': '2101',
    'L2J': '2101',
    'LI5': '2101',
    'LI8': '2101',
    'L2F': '2101',
    'LI6': '2101',
    'L2I': '2101',
    'L2B': '2101',
    'L2R': '2101',
    'LI2': '2101',
    'LI4': '2101',
    'LI7': '2101',
    'L2S': '2101',
    'L11': '2101',

    # Production site 0301
    'M81': '0301',
    'M82': '0301',
    'MQ1': '0301',
    'MQ2': '0301',
    'MR1': '0301',
    'MR2': '0301',
    'MR3': '0301',
    'MR4': '0301',
    'MEB': '0301',
    'MED': '0301',
    'MEE': '0301',
    'MEI': '0301',
    'MEH': '0301',
    'MEJ': '0301',
    'MEM': '0301',
    'MEN': '0301',
    'MEX': '0301',
    'M8M': '0301',
    'M84': '0301',
    'M71': '0301',
    'M72': '0301',
    'MQ4': '0301',
    'MNW': '0301',
    'MRR': '0301'
}

In [77]:
def create_paths(zsdkap_report_name, zsbe_report_name, mb5t_report_name, mb52_report_name, zkbp1_report_name):
    global ZSDKAP_FILE_PATH, ZSBE_FILE_PATH, MB5TD_2101, KPIS_FILE_PATH, MB52_FILE_PATH, ZKBP1_FILE_PATH
    # ZSDKAP_FILE_PATH = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty\28_PPS_KPI\excel_files/job/{zsdkap_report_name}.csv'
    # ZSBE_FILE_PATH = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty\28_PPS_KPI\excel_files/job/{zsbe_report_name}.xlsx'
    # MB5TD_2101 = fr'C:\Temp\Kamil\Prywatne\07_Programowanie\99_Moje_projekty/28_PPS_KPI\excel_files/job/{mb5t_report_name}.xlsx'
    # MB52_FILE_PATH = f'C:/Temp/Kamil/Prywatne/07_Programowanie/99_Moje_projekty/28_PPS_KPI/excel_files/job/{mb52_report_name}.xlsx'

    ZSDKAP_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zsdkap_report_name}.csv'
    ZSBE_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zsbe_report_name}.xlsx'
    MB5TD_2101 = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{mb5t_report_name}.xlsx'
    MB52_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{mb52_report_name}.xlsx'
    ZKBP1_FILE_PATH = fr'\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\02_MID_TERM_PLANNING_ALIGNMENT/{zkbp1_report_name}.xlsx'

In [78]:
zsdkap_dtypes = {
    'Odbiorca materia≈Ç√≥w': 'string',
    'Materia≈Ç': 'string',
    'Nazwa': 'string',
    'Dokument sprzeda≈ºy': 'string',
    'Pozycja': 'string',
    'Kontroler MRP': 'string',
    'Ilo≈õƒá zlecenia': 'string',
    # 'WA-Datum': 'datetime64[ns]',
}

zsdkap_new_columns_names = {
    'Odbiorca materia≈Ç√≥w': 'receiver',
    'Materia≈Ç': 'mat_number',
    'Nazwa': 'mat_description',
    'Dokument sprzeda≈ºy': 'customer_order_number',
    'Pozycja': 'customer_order_position',
    'Kontroler MRP': 'mrp_controller',
    'Ilo≈õƒá zlecenia': 'orders_quantity',
    'WADAT': 'dispatch_date_original'
}

vbap_new_columns_names = {
    'VBELN': 'customer_order_number',
    'POSNR': 'customer_order_position',
    'WERKS': 'delivery_plant'
}

In [79]:
zsdkap_report_name="zsdkap_20260622_REP_LU_PPS001A"
zsbe_report_name= "zsbe_mont"
mb5t_report_name= "MB5TD_0301"
mb52_report_name="mb52"
zkbp1_report_name='ZKBP1_SB_0301'

create_paths(zsdkap_report_name, zsbe_report_name, mb5t_report_name, mb52_report_name, zkbp1_report_name)

In [80]:
raw_df = pd.read_csv(ZSDKAP_FILE_PATH, dtype=zsdkap_dtypes, sep=';', encoding='MacRoman')
raw_df['WADAT'] = pd.to_datetime(raw_df['WADAT'], dayfirst=True, errors='coerce')
raw_df = raw_df.rename(columns=zsdkap_new_columns_names)

In [81]:
raw_df[['Kraj', 'mat_description', 'dispatch_date_original']].head(10)

  Kraj             mat_description dispatch_date_original
0   DE  EFL_R89PK_W_AL_673/1191_V2             2026-06-24
1   AT        ZRO_M_0664/1044_6x84             2026-06-26
2   NL           R69P_094/160_H200             2026-06-22
3   DE         I89G_134/140_K2EFZV             2026-06-23
4   DE         I89G_134/140_K2EFZV             2026-06-23
5   DE         I89G_134/140_K2EFZV             2026-06-23
6   DE         R89G_114/160_K2SAL3             2026-08-03
7   DE         R89G_094/160_K200L3             2026-08-03
8   DE       R89G_0650/1600_K200MW             2026-07-03
9   DE        ZRO_F_0650/1600_R6R8             2026-07-03

In [82]:
raw_df['production_site'] = raw_df['mrp_controller'].apply(lambda mrp: production_site_map.get(mrp))

In [83]:
raw_df[['Kraj', 'mat_description', 'dispatch_date_original', 'production_site', 'customer_order_number', 'customer_order_position']].head(10)

,Kraj,mat_description,dispatch_date_original,production_site,customer_order_number,customer_order_position
0,DE,EFL_R89PK_W_AL_673/1191_V2,2026-06-24,0301,0213925977,000030
1,AT,ZRO_M_0664/1044_6x84,2026-06-26,0301,2710152789,000010
2,NL,R69P_094/160_H200,2026-06-22,2101,4204007744,000031
3,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000011
4,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000021
5,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000031
6,DE,R89G_114/160_K2SAL3,2026-08-03,0301,0213926488,000021
7,DE,R89G_094/160_K200L3,2026-08-03,0301,0213926488,000051
8,DE,R89G_0650/1600_K200MW,2026-07-03,0301,0213915880,000011
9,DE,ZRO_F_0650/1600_R6R8,2026-07-03,0301,0213915880,000012

In [84]:
delivery_plants = get_delivery_plants_df(raw_df['customer_order_number'].tolist(), 1000, 100)

2026-06-23 10:36:48 | INFO     | SAP_CONN | Buduję parametry dla systemu P11_SSO: {'mshost': 'rffsp11s.sap.roto-frank.com', 'msserv': 'sapmsP11', 'sysid': 'P11', 'group': 'ROTO_FRANK', 'client': '151', 'lang': 'PL', 'snc_mode': '1', 'snc_qop': '8', 'snc_partnername': ' ', 'timeout': '300'}
2026-06-23 10:36:48 | INFO     | SAP_CONN | Połączenie z SAP nawiązane (system=P11_SSO).
2026-06-23 10:36:52 | INFO     | SAP_CONN | Połączenie SAP zamknięte (system=P11_SSO).

In [85]:
delivery_plants = delivery_plants.rename(columns=vbap_new_columns_names)
delivery_plants

      customer_order_number customer_order_position delivery_plant
0                0213895318                  000010           0301
1                0213895318                  000011           0301
2                0213895318                  000012           0301
3                0213895318                  000020           0301
4                0213895318                  000030           0301
...                     ...                     ...            ...
21229            4204007795                  000030           0301
21230            4204007795                  000040           0301
21231            4204007806                  000010           2101
21232            4204007806                  000020           2101
21233            4204007806                  000030           2101

[21234 rows x 3 columns]

In [86]:
raw_df = pd.merge(raw_df, delivery_plants, how='left', on=['customer_order_number', 'customer_order_position'])

In [87]:
raw_df[['Kraj', 'mat_description', 'dispatch_date_original', 'production_site', 'customer_order_number', 'customer_order_position', 'delivery_plant']].head(10)
# raw_df.to_excel("excel_files/output/raw_df_prod_sites.xlsx")
# TODO: Continue here - check how many items are without production site. Recalculate the date.

,Kraj,mat_description,dispatch_date_original,production_site,customer_order_number,customer_order_position,delivery_plant
0,DE,EFL_R89PK_W_AL_673/1191_V2,2026-06-24,0301,0213925977,000030,0301
1,AT,ZRO_M_0664/1044_6x84,2026-06-26,0301,2710152789,000010,0301
2,NL,R69P_094/160_H200,2026-06-22,2101,4204007744,000031,0301
3,NL,R69P_094/160_H200,2026-06-22,2101,4204007744,000031,0301
4,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000011,0301
5,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000011,0301
6,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000021,0301
7,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000021,0301
8,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000031,0301
9,DE,I89G_134/140_K2EFZV,2026-06-23,0301,0213924512,000031,0301

In [92]:
# Python: Monday=0 ... Sunday=6
TRANSPORT_ROUTES = {
    # Polska -> Francja
    ("2101", "1201"): [
        {"ship_day": 2, "arrival_day": 1},  # śr -> wt
        {"ship_day": 4, "arrival_day": 2},  # pt -> śr
    ],

    # Polska -> Czechy
    ("2101", "3701"): [
        {"ship_day": 1, "arrival_day": 3},  # wt -> czw
        {"ship_day": 4, "arrival_day": 1},  # pt -> wt
    ],

    # Polska -> Niemcy
    ("2101", "0301"): [
        {"ship_day": 0, "arrival_day": 3},  # pn -> czw
        {"ship_day": 1, "arrival_day": 4},  # wt -> pt
        {"ship_day": 2, "arrival_day": 0},  # śr -> pon
        {"ship_day": 3, "arrival_day": 1},  # czw -> wt
        {"ship_day": 4, "arrival_day": 2},  # pt -> śr

    ],

        # Niemcy -> Polska
    ("0301", "2101"): [
        {"ship_day": 0, "arrival_day": 2},  # pn -> śr
        {"ship_day": 1, "arrival_day": 3},  # wt -> czw
        {"ship_day": 2, "arrival_day": 4},  # śr -> pt
        {"ship_day": 3, "arrival_day": 0},  # czw -> pon
        {"ship_day": 4, "arrival_day": 1},  # pt -> wt

    ],

        # Niemcy -> Czechy
    ("0301", "3701"): [
        {"ship_day": 1, "arrival_day": 3},  # wt -> czw
        {"ship_day": 4, "arrival_day": 1},  # pt -> wt
    ],

        # Niemcy -> Francja
    ("0301", "1201"): [
        {"ship_day": 2, "arrival_day": 1},  # śr -> wt
        {"ship_day": 4, "arrival_day": 2},  # pt -> śr
    ],
}

In [93]:
from datetime import date, timedelta


def get_production_shipping_date(
        customer_ship_date: date,
        production_plant: str,
        destination_plant: str
) -> date:
    """
    Zwraca datę wysyłki z zakładu produkcyjnego.

    customer_ship_date - data wysyłki do klienta
    production_plant - kod zakładu produkcyjnego
    destination_plant - kod magazynu wysyłkowego
    """

    # Ten sam zakład -> brak transportu
    if production_plant == destination_plant:
        return customer_ship_date

    route = TRANSPORT_ROUTES.get((production_plant, destination_plant))

    if route is None:
        raise ValueError(
            f"Brak zdefiniowanej trasy {production_plant} -> {destination_plant}"
        )

    candidates = []

    for leg in route:
        arrival_day = leg["arrival_day"]
        ship_day = leg["ship_day"]

        # ile dni cofnąć do ostatniego wystąpienia dnia dostawy
        days_back = (customer_ship_date.weekday() - arrival_day) % 7

        arrival_date = customer_ship_date - timedelta(days=days_back)

        # obliczenie daty załadunku odpowiadającej tej dostawie
        transit_days = (arrival_day - ship_day) % 7
        if transit_days == 0:
            transit_days = 7

        production_ship_date = arrival_date - timedelta(days=transit_days)

        candidates.append(production_ship_date)

    # wybieramy najpóźniejszy możliwy załadunek
    return max(candidates)

In [98]:
# poniedziałek 22.06.2026
customer_ship_date = date(2026, 6, 22)
customer_ship_date = date(2026, 6, 23)  # wtorek

result = get_production_shipping_date(
    customer_ship_date,
    "0301",    # Polska
    "2101"     # Francja
)


print(result)

2026-06-19

In [100]:
raw_df.dropna(subset=['production_site', 'delivery_plant'], inplace=True)
raw_df['dispatch_date'] = raw_df.apply(
    lambda row: get_production_shipping_date(row['dispatch_date_original'], row['production_site'], row['delivery_plant']), axis=1)

In [101]:
raw_df[['Kraj', 'mat_description', 'dispatch_date_original', 'dispatch_date', 'production_site', 'customer_order_number', 'customer_order_position', 'delivery_plant']].head(10)

,Kraj,mat_description,dispatch_date_original,dispatch_date,production_site,customer_order_number,customer_order_position,delivery_plant
0,DE,EFL_R89PK_W_AL_673/1191_V2,2026-06-24,2026-06-24,0301,0213925977,000030,0301
1,AT,ZRO_M_0664/1044_6x84,2026-06-26,2026-06-26,0301,2710152789,000010,0301
2,NL,R69P_094/160_H200,2026-06-22,2026-06-17,2101,4204007744,000031,0301
3,NL,R69P_094/160_H200,2026-06-22,2026-06-17,2101,4204007744,000031,0301
4,DE,I89G_134/140_K2EFZV,2026-06-23,2026-06-23,0301,0213924512,000011,0301
5,DE,I89G_134/140_K2EFZV,2026-06-23,2026-06-23,0301,0213924512,000011,0301
6,DE,I89G_134/140_K2EFZV,2026-06-23,2026-06-23,0301,0213924512,000021,0301
7,DE,I89G_134/140_K2EFZV,2026-06-23,2026-06-23,0301,0213924512,000021,0301
8,DE,I89G_134/140_K2EFZV,2026-06-23,2026-06-23,0301,0213924512,000031,0301
9,DE,I89G_134/140_K2EFZV,2026-06-23,2026-06-23,0301,0213924512,000031,0301

In [102]:
raw_df.to_excel("excel_files/output/raw_df_calc_dates.xlsx", index=False)